version: '3.4'
services:
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 25432:5432
    volumes:
      - postgres_path:/var/lib/postgresql/db
volumes:
  postgres_path: